from typing import Any
from pydantic import BaseModel, Field
from typing import List, Optional

# ----> LLM output schema for all workflow
class WorkflowLLmOutput(BaseModel):
    next: bool = Field(...,description="True if the workflow can proceed to the next step.",)
    args: dict[str, Any] = Field(default_factory=dict,description="Arguments required for the next tool or workflow step.",)


# ------------wf2 llm output------------------------ 
class FailedCallJobMatchingOutput(BaseModel):
    next: bool
    cancelled_job_ids: list[str] = Field(default_factory=list)


#  -------------------- wf3 llm output schema -------------------------- 
class FollowUpJob(BaseModel):
    """Schema for a single follow-up job to be created"""
    call_id: str = Field(description="ID of the source call")
    customer_name: str = Field(description="Customer name from the call")
    phone_number: str = Field(description="Customer phone number")
    issue_summary: str = Field(description="Brief summary of the issue that needs follow-up")
    job_type: str = Field(description="Type of job to create (e.g., Callback, Technical Support, Product Replacement)")
    priority: str = Field(description="Priority level: low, medium, high, or critical")

class FollowUpJobCreationOutput(BaseModel):
    """LLM output schema for follow-up job creation workflow"""
    jobs_to_create: List[FollowUpJob] = Field(default=[],description="List of jobs to be created from follow-up required calls")
    summary: Optional[str] = Field(default=None,description="Optional summary of the follow-up jobs identified")


# ------------------------------ wf4 llm output schema ------------------
class GeneratedJobData(BaseModel):
    """Schema for LLM-generated job data from a pending call"""
    call_id: str = Field(description="ID of the source pending call")
    customer_name: str = Field(description="Customer name from the call")
    job_title: str = Field(description="Professional job title generated by LLM")
    job_description: str = Field(description="Detailed job description with actionable steps")
    priority: str = Field(description="Priority level: low, medium, high, or critical")
    priority_reasoning: str = Field(description="Explanation for why this priority level was chosen")

class PendingCallsJobGenerationOutput(BaseModel):
    """LLM output schema for pending calls job generation"""
    jobs: List[GeneratedJobData] = Field(default=[],description="List of jobs generated from pending calls by LLM")
    workflow_summary: Optional[str] = Field(default=None,description="Overall summary of the workflow and jobs generated")


# --------------------- wf5 llm schema for stats draft-------------------------------
class CallStatsReportGenerationOutput(BaseModel):
    """LLM output schema for comprehensive call statistics and job report"""
    call_statistics_summary: str = Field(description="Summary of call statistics by status and outcome")
    job_statistics_summary: str = Field(description="Summary of open jobs by priority and assignment status")
    correlation_analysis: str = Field(description="Analysis of correlation between calls and jobs")
    critical_observations: List[str] = Field(default=[],description="List of critical observations and potential issues")
    recommendations: List[str] = Field(default=[],description="List of actionable recommendations")
    overall_summary: str = Field(description="Executive summary of operational health and key findings")
